# -*- coding: utf-8 -*-
"""MakineSınıflandırma.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18flMSc-sDlgO5B-Vd7GGo39d7Z8B8RYF
"""

# Google Drive'a bağlanmak için gerekli kütüphaneleri import edin
from google.colab import drive

# Google Drive'a bağlanın
drive.mount('/content/drive')

import os
import cv2
import numpy as np
from sklearn.neighbors import KNeighborsClassifier


# Görüntüleri oku
X = [] # Özellikleri saklamak için bir liste oluşturun
y = [] # Etiketleri saklamak için bir liste oluşturun
for label in os.listdir('/content/drive/MyDrive/makine/train'): # Eğitim verisi için her klasörü dolaş
    for image_file in os.listdir(f'/content/drive/MyDrive/makine/train/{label}'): # Klasör içindeki her resmi dolaş
        image = cv2.imread(f'/content/drive/MyDrive/makine/train/{label}/{image_file}')
        image = cv2.resize(image, (200, 200)) # Ölçeklendirin
        gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY) # Gri seviyeye dönüştürün
        hog = cv2.HOGDescriptor() # HOG verilerini üretin
        feature = hog.compute(gray)
        X.append(feature)
        y.append(label) # Etiketi ekleyin

# Sınıflandırıcıyı eğitin
X = np.array(X)
y = np.array(y)
clf = KNeighborsClassifier()
clf.fit(X, y)

# Yeni bir görüntü için tahmin yapın
test_image = cv2.imread('test.jpg')
test_image = cv2.resize(test_image, (200, 200))
test_gray = cv2.cvtColor(test_image, cv2.COLOR_BGR2GRAY)
test_hog = cv2.HOGDescriptor()
test_feature = test_hog.compute(test_gray)
prediction = clf.predict(test_feature)
print("Tahmin:", prediction)